### PR TITLE
eact_todo-app-with-api (finally part )

### PR DESCRIPTION
**Pull request by georgiyevv**
[DEMO LINK](https://svyatoslavPy.github.io/react_todo-app-with-api/)

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your code
You need to fix this failed test.
You need to disable input until we get a response from the server
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Consider keeping the entered text in the input if the request fails and removing a temporary todo. 
Screenshot 2024-05-09 at 14 22 55

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Consider removing the temporary todo if the request fails 
Screenshot 2024-05-09 at 15 35 18

**Review by ghost — APPROVED** [review]
Good job!

**Pull request closed without merging**
